name: CI-CD

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: DVC Pull
        run: |
          dvc pull

      - name: Run Streamlit Application
        run: |
          nohup streamlit run app.py --server.port 8000 > streamlit.log 2>&1 &
          echo $! > streamlit_pid.txt
          sleep 15

      - name: Run Tests
        run: pytest test_app.py -v
        env:
          STREAMLIT_SERVER_URL: http://localhost:8000

      - name: Stop Streamlit Application
        if: always()
        run: |
          kill $(cat streamlit_pid.txt) || echo "No Streamlit process found"
          rm -f streamlit_pid.txt

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          content: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spotify_hybrid_recommender_system:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spotify_hybrid_recommender_system:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout

